### ISSUE TITLE
Doesn't work with getters and setters

### ISSUE THREAD

**Issue by jhancock4d** [flankb/nameof#1]
It generates duplicates and weird syntax.

i.e.:

```
static const String propertyGetFirstName = 'firstName';
static const String propertySetFirstName= = 'firstName';
static const String propertyGetLastName = 'lastName';
static const String propertySetLastName= = 'lastName';

```

And @nameOfIgnore doesn't do anything with getters and setters.

It should create a single entry just called propertyFirstName and another propertyLastName and that's it.

**Comment by flankb** [comment]
Hello, @jhancock4d ! Can you get me the full example with source code of class that marked with `nameof ` annotation?

**Comment by jhancock4d** [comment]
```
@nameOf
class ContactViewModel extends INotifyPropertyChanged<ContactModel> {
  ContactViewModel._(ContactModel model) : super(model);

  static Future<ContactViewModel> create({String? id}) async {
        ....
  }

  String get firstName => model.firstName;
  set firstName(String value) =>
      setProperty((value) => model.firstName = value, value, propertyFirstName);

  String get lastName => model.lastName;
  set lastName(String value) =>
      setProperty((value) => model.lastName = value, value, propertyLastName);

  Future<void> save() async {
    return;
  }

```

**Comment by flankb** [comment]
@jhancock4d Since the properties under the hood are separate methods, this is normal generator behavior. The generated code shows that the source class has getters and setters. Since their names are the same, you can use either `propertyGet...` or `propertySet...`.

**Comment by jhancock4d** [comment]
In my cause the genned file had errors because it had double = in the setter.

And the code should be smart enough to roll this up, because they aren't really separate anything, they're a property with getter/setter.

**Comment by flankb** [comment]
@jhancock4d I have updated the package with a fix for the generation bug with the "=" character in the setters. New version is 0.1.3. Thanks for bug report!

**Comment by flankb** [comment]
And I made fix for nameof ignore for props. You can mark setter with `@NameofIgnore()` annotation. Last version is 0.1.4.

**Comment by jhancock4d** [comment]
Nice! Thanks!

**Comment by flankb** [comment]
Thanks for report! Do you have another questions?

**Comment by jhancock4d** [comment]
Nope. I'm good. Thanks for doing this project!
