### ISSUE TITLE
[Request] Upgrade version of analyzer dependency

### ISSUE THREAD

**Issue by balazsszekely** [flankb/nameof#2]
Hi,

thanks for this package, it seems really useful :). But unfortunately I cannot use it, because it conflicts with the latest freezed package:

```
Because nameof >=0.1.2 depends on analyzer >=2.0.0 <5.0.0 and nameof <0.1.2 depends on analyzer >=3.0.0 <5.0.0, every version of nameof requires analyzer >=2.0.0 <5.0.0.
And because freezed >=2.2.1 depends on analyzer ^5.2.0, freezed >=2.2.1 is incompatible with nameof.
So, because flutter_client depends on both freezed ^2.3.2 and nameof any, version solving failed.
pub finished with exit code 65
```

It would be great, if you could update the package to make it compatible with the newer version of analyzer.

Thanks,
Balazs

**Comment by flankb** [comment]
Hello! I've updated the version of analyzer in new nameof 0.2.2
